local cursor = "0"
local sum = 0

repeat
    local result = redis.call('ZSCAN', KEYS[1], cursor)
    cursor = result[1]
    local members = result[2]

    for i = 1, #members, 2 do
        -- local member = members[i]
        local score = members[i + 1]
        
        sum = sum + score 
    end
until cursor == "0"

return sum

-- Generated by ChatGPT