
const fs = require('fs');

// Read the file with SQL INSERT statements
fs.readFile('sql_inserts.sql', 'utf8', (err, data) => {
  if (err) {
    console.error(err);
    return;
  }

  // Split the file content into individual SQL statements
  const sqlStatements = data.split(';');

  // Iterate over each SQL statement and convert it to Redis HSET statement
  sqlStatements.forEach((sqlStatement) => {
    if (sqlStatement.trim() !== '') {
      // Extract the table name, column names, and values from the SQL statement
      const tableName = sqlStatement.match(/INSERT INTO (\w+)/i)[1];
      const columnNames = sqlStatement.match(/\((.+?)\)/i)[1].split(',').map((name) => name.trim());
      const values = sqlStatement.match(/VALUES \((.+?)\)/i)[1].split(',').map((value) => value.trim());

      // Construct the Redis HSET statement
      let redisHSETStatement = `HSET cvt:${tableName}:`;

      columnNames.forEach((columnName, index) => {
        if (index === 0) 
          redisHSETStatement += `${values[index]} `;
        redisHSETStatement += `${columnName} ${values[index]} `;
      });

      console.log(redisHSETStatement.trim());
    }
  });
});

/*
   Generated by Chat-GPT
*/