version: "3.3"
services:
  redis:
    container_name: redis_ru204
    image: redis/redis-stack-server:6.2.6-v12
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - ./redisdata:/data
    environment:
      - REDIS_ARGS=--appendonly yes --save ""

  mysql:
    container_name: mysql_ru204
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - ./mysqldata:/var/lib/mysql
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=moviedb
      - MYSQL_ROOT_PASSWORD=root

#
# How to use MySQL with Docker and Docker compose a beginners guide
# https://geshan.com.np/blog/2022/02/mysql-docker-compose/
#
# How to Fix "Access denied for user root@localhost" MySQL Error
# https://phoenixnap.com/kb/access-denied-for-user-root-localhost
#
# mysql -u root -p -h 127.0.0.1
#