const leonard = {
    name: "Dr. Leonard Hofstadter",
    gender: "Male",
    age: "30s",
    hobby: "Physics"
  }
const sheldon = {
    name: "Dr. Sheldon Cooper",
    gender: "Male",
    age: "30s",
    hobby: "Theoretical Physics, Comic Books"
  }
const penny = {
    name: "Penny",
    gender: "Female",
    age: "Late 20s to early 30s",
    hobby: "Acting, Socializing"
  }
const rajesh = {
    name: "Dr. Rajesh Koothrappali",
    gender: "Male",
    age: "30s",
    hobby: "Astrophysics, Collecting Action Figures"
  }
const howard = {
    name: "Dr. Howard Wolowitz",
    gender: "Male",
    age: "30s",
    hobby: "Engineering, Magic Tricks"
  }
const bernadette = {
    name: "Bernadette Rostenkowski-Wolowitz",
    gender: "Female",
    age: "Late 20s to early 30s",
    hobby: "Microbiology, Pharmaceutical Sales"
  }
const amy = {
    name: "Amy Farrah Fowler",
    gender: "Female",
    age: "30s",
    hobby: "Neurobiology, Blossoming Romance"
  }
const stuart = {
    name: "Stuart Bloom",
    gender: "Male",
    age: "30s",
    hobby: "Running Comic Book Store"
  }
const leslie = {
    name: "Leslie Winkle",
    gender: "Female",
    age: "30s",
    hobby: "Physics, Experimental Research"
  }
const barry = {
    name: "Barry Kripke",
    gender: "Male",
    age: "30s",
    hobby: "Physics, Playing Pranks"
  }

export { leonard, sheldon, rajesh, howard, penny, bernadette, amy, stuart, leslie, barry }  

/*
   Generated by Chat-GPT
*/